import { CalendarDays, FileText, Newspaper, ShieldAlert, Sparkles } from 'lucide-react';
import { Link } from 'react-router-dom';

const events = [
  { date:'09/01', type:'同行财报', company:'浪潮信息', title:'2026年半年度报告', impact:'更新可比公司收入增速、利润率与交易倍数', tone:'positive', source:'深交所公告' },
  { date:'09/03', type:'行业政策', company:'华辰智算', title:'算力基础设施建设指引窗口', impact:'评估募投项目产能利用率及市场容量假设', tone:'neutral', source:'工信部公开信息' },
  { date:'09/05', type:'IPO审核', company:'行业', title:'同赛道申报企业问询回复', impact:'补充客户集中度、经销模式和收入确认核查', tone:'risk', source:'交易所公开信息' },
  { date:'09/08', type:'可比交易', company:'行业', title:'算力企业战略融资披露', impact:'纳入先例交易倍数并复核控制权与流动性差异', tone:'positive', source:'公开交易披露' },
];

export default function CatalystRadar(){return <div className="mx-auto max-w-[1400px] space-y-4">
  <header className="flex flex-col gap-3 border-b border-t-border pb-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-2 text-xs text-t-textDim"><Newspaper className="h-4 w-4 text-t-cyan" />Deal Intelligence</div><h1 className="mt-2 text-2xl font-semibold text-t-textBright">公告与行业情报</h1><p className="mt-2 text-sm text-t-textDim">将同行公告、IPO审核、政策与交易事件映射至尽调问题和估值假设。</p></div><Link to="/capital/assistant" className="inline-flex w-fit items-center gap-2 rounded-md bg-t-cyan px-3 py-2 text-xs font-medium text-slate-950"><Sparkles className="h-4 w-4" />生成本周事件摘要</Link></header>
  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[['本周事件','12项','4项影响项目'],['同业公告','3家公司','2项需更新估值'],['审核动态','5项','收入与客户核验'],['风险事件','2项','政策与合规']].map(([label,value,detail])=><div key={label} className="panel p-4"><div className="text-[11px] text-t-textDim">{label}</div><div className="mt-2 font-mono text-xl font-semibold text-t-textBright">{value}</div><div className="mt-1 text-[11px] text-t-cyan">{detail}</div></div>)}</section>
  <section className="grid gap-4 xl:grid-cols-[1fr_360px]"><div className="panel overflow-hidden"><div className="border-b border-t-border px-4 py-3"><h2 className="flex items-center gap-2 text-sm font-semibold text-t-textBright"><CalendarDays className="h-4 w-4 text-t-blue" />关键事件日历</h2></div><div className="divide-y divide-t-border">{events.map(event=><div key={event.title} className="grid gap-3 p-4 sm:grid-cols-[60px_82px_100px_1fr]"><div className="font-mono text-sm text-t-textBright">{event.date}</div><div><span className={`rounded px-2 py-1 text-[10px] ${event.tone==='risk'?'bg-t-red/10 text-t-red':event.tone==='positive'?'bg-t-green/10 text-t-green':'bg-t-blue/10 text-t-blue'}`}>{event.type}</span></div><div className="text-xs text-t-text">{event.company}</div><div><h3 className="text-xs font-medium text-t-textBright">{event.title}</h3><p className="mt-1 text-xs leading-5 text-t-textDim">{event.impact}</p><div className="mt-2 flex items-center gap-1 text-[10px] text-t-textDim"><FileText className="h-3 w-3" />{event.source}</div></div></div>)}</div></div><aside className="space-y-4"><div className="panel p-4"><h2 className="flex items-center gap-2 text-sm font-semibold text-t-textBright"><Sparkles className="h-4 w-4 text-t-yellow" />项目影响提示</h2><div className="mt-4 space-y-3">{['同业增速变化将影响上市可比公司倍数与折溢价','审核问询案例进入尽调程序和招股书核查清单','交易案例需区分少数股权、控制权和协同溢价'].map((item,index)=><div key={item} className="flex gap-2 text-xs leading-5 text-t-text"><span className="font-mono text-t-cyan">0{index+1}</span>{item}</div>)}</div></div><div className="rounded-lg border border-t-yellow/30 bg-t-yellow/5 p-4"><div className="flex items-center gap-2 text-sm font-medium text-t-yellow"><ShieldAlert className="h-4 w-4" />来源与合规</div><p className="mt-2 text-xs leading-5 text-t-textDim">AI摘要不替代原文、律师意见、审计证据或项目组专业判断。</p></div></aside></section>
</div>}
