import { useMemo, useState } from 'react';
import { BarChart3, Check, Filter, Scale } from 'lucide-react';
import { comparableCompanies, median } from '../data/advisoryModel';
import { useResearchModel } from '../context/ResearchModelContext';

export default function ComparableCompanies() {
  const { model, assumptions } = useResearchModel();
  const [selected, setSelected] = useState(() => new Set(comparableCompanies.filter(item => item.selected).map(item => item.code)));
  const [showFilters, setShowFilters] = useState(false);
  const active = useMemo(() => comparableCompanies.filter(item => selected.has(item.code) && item.code !== '603019.SH'), [selected]);
  const metrics = useMemo(() => ({ evRevenue: median(active.map(item => item.evRevenue)), evEbitda: median(active.map(item => item.evEbitda)), pe: median(active.map(item => item.pe)), roe: median(active.map(item => item.roe)) }), [active]);
  const evEbitdaPrice = (model[0].ebitda * metrics.evEbitda - assumptions.netDebt) / assumptions.shares;
  const pePrice = model[0].eps * metrics.pe;
  const midpoint = median([evEbitdaPrice, pePrice]);
  const toggle = (code: string) => setSelected(current => { const next = new Set(current); next.has(code) ? next.delete(code) : next.add(code); return next; });
  return (
    <div className="mx-auto max-w-[1500px] space-y-4">
      <header className="flex flex-col gap-3 border-b border-t-border pb-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-2 text-xs text-t-textDim"><Scale className="h-4 w-4 text-t-cyan" />Trading Comparables · 中科曙光 603019.SH</div><h1 className="mt-2 text-2xl font-semibold text-t-textBright">上市可比公司估值</h1><p className="mt-2 text-sm text-t-textDim">根据业务重合度、成长性和盈利能力选择样本，将FY2026E倍数应用于统一经营模型。</p></div><button onClick={()=>setShowFilters(value=>!value)} className="inline-flex w-fit items-center gap-2 rounded-md border border-t-border bg-t-panel px-3 py-2 text-xs text-t-text"><Filter className="h-4 w-4" />{showFilters?'收起筛选':'筛选条件'}</button></header>
      {showFilters&&<section className="panel grid gap-3 p-4 sm:grid-cols-4">{[['业务重合度','算力基础设施 ≥ 50%'],['收入规模','10–500亿元'],['收入增速','≥ 8%'],['盈利状态','EBITDA为正']].map(([label,value])=><label key={label} className="text-[11px] text-t-textDim">{label}<div className="mt-2 rounded-md border border-t-border bg-t-bg px-3 py-2 text-xs text-t-text">{value}</div></label>)}</section>}
      <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[['EV/Revenue',`${metrics.evRevenue.toFixed(1)}x`,'样本中位数'],['EV/EBITDA',`${metrics.evEbitda.toFixed(1)}x`,'核心估值指标'],['P/E',`${metrics.pe.toFixed(1)}x`,'Forward 12M'],['ROE',`${metrics.roe.toFixed(1)}%`,'盈利质量参照']].map(([label,value,detail]) => <div key={label} className="panel p-4"><div className="text-[11px] text-t-textDim">{label}</div><div className="mt-2 font-mono text-xl font-semibold text-t-cyan">{value}</div><div className="mt-1 text-[11px] text-t-textDim">{detail}</div></div>)}</section>
      <section className="panel overflow-hidden"><div className="flex items-center justify-between border-b border-t-border px-4 py-3"><div><h2 className="flex items-center gap-2 text-sm font-semibold text-t-textBright"><BarChart3 className="h-4 w-4 text-violet-300" />可比公司矩阵</h2><p className="mt-1 text-[11px] text-t-textDim">已选择 {selected.size} 家公司</p></div><span className="rounded bg-t-blue/10 px-2 py-1 text-[10px] text-t-blue">FY2026E</span></div><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-right text-xs"><thead className="bg-white/[0.02] text-t-textDim"><tr>{['选择','公司','股价','收入增速','EBITDA Margin','EV/Revenue','EV/EBITDA','P/E','ROE'].map((item,index) => <th key={item} className={`px-4 py-3 font-medium ${index < 2 ? 'text-left' : ''}`}>{item}</th>)}</tr></thead><tbody className="divide-y divide-t-border">{comparableCompanies.map(company => <tr key={company.code} className={company.code === '603019.SH' ? 'bg-t-cyan/[0.035]' : 'hover:bg-white/[0.015]'}><td className="px-4 py-3 text-left"><button onClick={() => toggle(company.code)} className={`flex h-5 w-5 items-center justify-center rounded border ${selected.has(company.code) ? 'border-t-cyan bg-t-cyan text-slate-950' : 'border-t-border'}`}>{selected.has(company.code) && <Check className="h-3.5 w-3.5" />}</button></td><td className="px-4 py-3 text-left"><div className="font-medium text-t-textBright">{company.name}</div><div className="mt-0.5 font-mono text-[10px] text-t-textDim">{company.code}</div></td><td className="px-4 py-3 font-mono text-t-text">¥{company.price.toFixed(2)}</td><td className="px-4 py-3 font-mono text-t-green">+{company.revenueGrowth.toFixed(1)}%</td><td className="px-4 py-3 font-mono text-t-text">{company.ebitdaMargin.toFixed(1)}%</td><td className="px-4 py-3 font-mono text-t-text">{company.evRevenue.toFixed(1)}x</td><td className="px-4 py-3 font-mono text-t-text">{company.evEbitda.toFixed(1)}x</td><td className="px-4 py-3 font-mono text-t-text">{company.pe.toFixed(1)}x</td><td className="px-4 py-3 font-mono text-t-text">{company.roe.toFixed(1)}%</td></tr>)}</tbody></table></div></section>
      <section className="grid gap-4 lg:grid-cols-3">{[['EV/EBITDA隐含价',`¥${evEbitdaPrice.toFixed(2)}`,`${metrics.evEbitda.toFixed(1)}x × 2026E EBITDA`],['相对估值中枢',`¥${midpoint.toFixed(2)}`,'EV/EBITDA与P/E中位数'],['P/E隐含价',`¥${pePrice.toFixed(2)}`,`${metrics.pe.toFixed(1)}x × 2026E EPS`]].map(([label,value,detail],index) => <div key={label} className={`rounded-lg border p-4 ${index===1?'border-t-cyan/40 bg-t-cyan/5':'border-t-border bg-t-panel'}`}><div className="text-[11px] text-t-textDim">{label}</div><div className="mt-2 font-mono text-2xl font-semibold text-t-textBright">{value}</div><div className="mt-1 text-[11px] text-t-textDim">{detail}</div></div>)}</section>
    </div>
  );
}
