import { useState } from 'react';
import { Building2, ChevronRight, ClipboardList, Plus, Search, X } from 'lucide-react';
import { Link } from 'react-router-dom';

const seedProjects = [
  { name:'华辰智算科技有限公司', code:'AWC-2026-03', type:'A股IPO', stage:'尽调与规范整改', owner:'刘宇森', updated:'今天 14:20', risk:'中', progress:68 },
  { name:'澄岳工业软件有限公司', code:'AWC-2026-07', type:'Pre-IPO融资', stage:'商业尽调', owner:'陈晟', updated:'今天 10:18', risk:'低', progress:42 },
  { name:'海岚精密制造集团', code:'AWC-2026-09', type:'卖方M&A', stage:'信息备忘录', owner:'王珂', updated:'昨天 18:45', risk:'中', progress:56 },
  { name:'远辰新能源股份', code:'AWC-2026-11', type:'公司债', stage:'信用与偿债测算', owner:'刘宇森', updated:'08/28 16:20', risk:'高', progress:31 },
];

export default function CoveragePipeline(){
  const [projects,setProjects]=useState(seedProjects);
  const [query,setQuery]=useState('');
  const [adding,setAdding]=useState(false);
  const [name,setName]=useState('');
  const filtered=projects.filter(item => `${item.name}${item.code}${item.type}`.toLowerCase().includes(query.toLowerCase()));
  const addProject=()=>{if(!name.trim())return;setProjects(current=>[{name:name.trim(),code:`AWC-2026-${String(current.length+12).padStart(2,'0')}`,type:'待确定',stage:'立项评估',owner:'刘宇森',updated:'刚刚',risk:'待评估',progress:5},...current]);setName('');setAdding(false);};
  return <div className="mx-auto max-w-[1400px] space-y-4">
    <header className="flex flex-col gap-3 border-b border-t-border pb-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-2 text-xs text-t-textDim"><ClipboardList className="h-4 w-4 text-t-cyan" />Deal Pipeline</div><h1 className="mt-2 text-2xl font-semibold text-t-textBright">投行项目管线</h1><p className="mt-2 text-sm text-t-textDim">统一跟踪IPO、Pre-IPO融资、M&amp;A与债券项目的阶段、风险、负责人和下一步动作。</p></div><button onClick={()=>setAdding(true)} className="inline-flex w-fit items-center gap-2 rounded-md bg-t-cyan px-3 py-2 text-xs font-medium text-slate-950"><Plus className="h-4 w-4" />新增项目</button></header>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[['活跃项目',`${projects.length}个`,'3类交易'],['IPO项目','1个','尽调进行中'],['本周里程碑','5项','2项临近截止'],['高风险事项','1项','需MD关注']].map(([label,value,detail])=><div key={label} className="panel p-4"><div className="text-[11px] text-t-textDim">{label}</div><div className="mt-2 font-mono text-xl font-semibold text-t-textBright">{value}</div><div className="mt-1 text-[11px] text-t-cyan">{detail}</div></div>)}</section>
    <section className="panel overflow-hidden"><div className="flex flex-col gap-3 border-b border-t-border px-4 py-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-sm font-semibold text-t-textBright">当前Mandates</h2><p className="mt-1 text-[11px] text-t-textDim">所有名称与数据均为虚构演示</p></div><div className="flex items-center gap-2 rounded-md border border-t-border bg-white/[0.015] px-3 py-2"><Search className="h-3.5 w-3.5 text-t-textDim" /><input value={query} onChange={event=>setQuery(event.target.value)} className="w-56 bg-transparent text-xs text-t-text outline-none" placeholder="搜索项目、编号或交易类型" /></div></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-xs"><thead className="bg-white/[0.02] text-t-textDim"><tr>{['项目','交易类型','当前阶段','风险','负责人','最后更新','完成度',''].map(item=><th key={item} className="px-4 py-3 font-medium">{item}</th>)}</tr></thead><tbody className="divide-y divide-t-border">{filtered.map(project=><tr key={project.code} className="hover:bg-white/[0.015]"><td className="px-4 py-3"><div className="flex items-center gap-3"><span className="flex h-8 w-8 items-center justify-center rounded bg-t-cyan/10 text-t-cyan"><Building2 className="h-4 w-4" /></span><div><div className="font-medium text-t-textBright">{project.name}</div><div className="mt-0.5 font-mono text-[10px] text-t-textDim">{project.code}</div></div></div></td><td className="px-4 py-3 text-t-text">{project.type}</td><td className="px-4 py-3 text-t-textDim">{project.stage}</td><td className="px-4 py-3"><span className={`rounded px-2 py-1 text-[10px] ${project.risk==='高'?'bg-t-red/10 text-t-red':project.risk==='中'?'bg-t-yellow/10 text-t-yellow':'bg-t-green/10 text-t-green'}`}>{project.risk}</span></td><td className="px-4 py-3 text-t-textDim">{project.owner}</td><td className="px-4 py-3 text-t-textDim">{project.updated}</td><td className="px-4 py-3"><div className="flex items-center gap-2"><div className="h-1.5 w-20 rounded bg-white/[0.05]"><div className="h-full rounded bg-gradient-to-r from-t-blue to-t-cyan" style={{width:`${project.progress}%`}} /></div><span className="font-mono text-[10px] text-t-textDim">{project.progress}%</span></div></td><td className="px-4 py-3">{project.code==='AWC-2026-03'?<Link to="/capital" className="text-t-cyan"><ChevronRight className="h-4 w-4" /></Link>:<button onClick={()=>alert('演示项目已登记，详细工作台将在资料齐备后启用。')} className="text-t-textDim"><ChevronRight className="h-4 w-4" /></button>}</td></tr>)}</tbody></table></div></section>
    {adding&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/65 p-4"><div className="w-full max-w-md rounded-xl border border-t-border bg-t-panel p-5 shadow-2xl"><div className="flex items-center justify-between"><h2 className="text-base font-semibold text-t-textBright">新增投行项目</h2><button onClick={()=>setAdding(false)}><X className="h-4 w-4 text-t-textDim" /></button></div><label className="mt-5 block text-xs text-t-textDim">目标公司 / 项目名称<input autoFocus value={name} onChange={event=>setName(event.target.value)} onKeyDown={event=>event.key==='Enter'&&addProject()} className="mt-2 w-full rounded-md border border-t-border bg-t-bg px-3 py-2.5 text-sm text-t-text outline-none focus:border-t-cyan" placeholder="例如：星河半导体有限公司" /></label><div className="mt-5 flex justify-end gap-2"><button onClick={()=>setAdding(false)} className="rounded-md border border-t-border px-3 py-2 text-xs text-t-textDim">取消</button><button onClick={addProject} className="rounded-md bg-t-cyan px-3 py-2 text-xs font-medium text-slate-950">创建项目</button></div></div></div>}
  </div>;
}
