import { BarChart3, CheckCircle2, GitCompareArrows, SlidersHorizontal } from 'lucide-react';
import { calculateResearchDcf, scenarioPresets, type ModelScenario } from '../data/researchModel';
import { useResearchModel } from '../context/ResearchModelContext';

const labels: Record<ModelScenario,string>={bear:'Bear Case',base:'Base Case',bull:'Bull Case'};

export default function ModelVersions(){
  const {scenario,setScenario}=useResearchModel();
  const cases=(['bear','base','bull'] as ModelScenario[]).map(key=>({key,assumptions:scenarioPresets[key],dcf:calculateResearchDcf(scenarioPresets[key])}));
  const base=cases[1];
  return <div className="mx-auto max-w-[1350px] space-y-4">
    <header className="flex flex-col gap-3 border-b border-t-border pb-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-2 text-xs text-t-textDim"><SlidersHorizontal className="h-4 w-4 text-t-cyan" />Scenario Lab · 中科曙光</div><h1 className="mt-2 text-2xl font-semibold text-t-textBright">Bear / Base / Bull情景分析</h1><p className="mt-2 text-sm text-t-textDim">比较经营驱动、盈利预测和DCF目标价变化，识别估值结论最敏感的假设。</p></div><div className="rounded-md border border-t-border bg-t-panel px-3 py-2 text-xs text-t-textDim">当前应用：<strong className="ml-1 text-t-cyan">{labels[scenario]}</strong></div></header>

    <section className="grid gap-4 lg:grid-cols-3">{cases.map((item,index)=>{const first=item.dcf.forecast[0];const last=item.dcf.forecast[4];return <article key={item.key} className={`panel overflow-hidden ${scenario===item.key?'border-t-cyan/50':''}`}><div className={`border-b px-4 py-3 ${index===0?'border-t-red/20 bg-t-red/[0.035]':index===1?'border-t-cyan/20 bg-t-cyan/[0.035]':'border-t-green/20 bg-t-green/[0.035]'}`}><div className="flex items-center justify-between"><h2 className="text-sm font-semibold text-t-textBright">{labels[item.key]}</h2>{scenario===item.key&&<CheckCircle2 className="h-4 w-4 text-t-cyan" />}</div><p className="mt-1 text-[10px] text-t-textDim">{index===0?'需求与利润率承压':index===1?'核心经营假设':'需求上行与经营杠杆释放'}</p></div><div className="grid grid-cols-2 gap-3 p-4 text-xs">{[
          ['2026E收入',`¥${first.revenue.toFixed(1)}亿`],['2030E收入',`¥${last.revenue.toFixed(1)}亿`],['2026E EPS',`¥${first.eps.toFixed(2)}`],['2030E FCFF',`¥${last.fcff.toFixed(1)}亿`],['WACC',`${(item.assumptions.wacc*100).toFixed(1)}%`],['DCF目标价',`¥${item.dcf.pricePerShare.toFixed(2)}`],
        ].map(([label,value])=><div key={label} className="rounded border border-t-border bg-white/[0.012] p-3"><div className="text-[10px] text-t-textDim">{label}</div><div className="mt-1.5 font-mono text-t-textBright">{value}</div></div>)}</div><button onClick={()=>setScenario(item.key)} className={`mx-4 mb-4 w-[calc(100%-2rem)] rounded-md py-2 text-xs ${scenario===item.key?'bg-t-cyan text-slate-950':'border border-t-border text-t-text hover:border-t-cyan/40'}`}>{scenario===item.key?'已应用到全部模型':'应用此情景'}</button></article>})}</section>

    <section className="panel overflow-hidden"><div className="border-b border-t-border px-4 py-3"><h2 className="flex items-center gap-2 text-sm font-semibold text-t-textBright"><GitCompareArrows className="h-4 w-4 text-violet-300" />核心假设对比</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-right text-xs"><thead className="bg-white/[0.02] text-t-textDim"><tr><th className="px-4 py-3 text-left font-medium">假设</th>{cases.map(item=><th key={item.key} className="px-4 py-3 font-medium">{labels[item.key]}</th>)}</tr></thead><tbody className="divide-y divide-t-border">{[
      ['IT设备收入增速','itGrowth'],['软件服务收入增速','servicesGrowth'],['IT设备毛利率','itGrossMargin'],['软件服务毛利率','servicesGrossMargin'],['研发费用率','rdPct'],['WACC','wacc'],['永续增长率','terminalGrowth'],
    ].map(([label,key])=><tr key={key}><td className="px-4 py-3 text-left text-t-text">{label}</td>{cases.map(item=><td key={item.key} className={`px-4 py-3 font-mono ${item.key==='base'?'text-t-cyan':'text-t-text'}`}>{((item.assumptions[key as keyof typeof item.assumptions] as number)*100).toFixed(1)}%</td>)}</tr>)}</tbody></table></div></section>

    <section className="grid gap-4 xl:grid-cols-[1fr_360px]"><div className="panel p-4"><h2 className="flex items-center gap-2 text-sm font-semibold text-t-textBright"><BarChart3 className="h-4 w-4 text-t-green" />目标价情景桥</h2><div className="mt-5 space-y-4">{cases.map(item=><div key={item.key} className="grid grid-cols-[90px_1fr_80px] items-center gap-3 text-xs"><span className="text-t-textDim">{labels[item.key]}</span><div className="h-3 rounded bg-white/[0.05]"><div className={`h-full rounded ${item.key==='bear'?'bg-t-red/70':item.key==='base'?'bg-t-cyan':'bg-t-green/70'}`} style={{width:`${Math.min(100,item.dcf.pricePerShare/base.dcf.pricePerShare*62)}%`}} /></div><span className="text-right font-mono text-t-textBright">¥{item.dcf.pricePerShare.toFixed(2)}</span></div>)}</div></div><aside className="panel p-4"><div className="text-[10px] uppercase tracking-[0.16em] text-t-textDim">关键敏感项</div><div className="mt-4 space-y-3 text-xs leading-5">{['IT设备收入恢复速度决定收入规模。','软件服务毛利率决定盈利弹性。','WACC和永续增长率决定终值及目标价区间。'].map((item,index)=><div key={item} className="flex gap-2"><span className="font-mono text-t-cyan">0{index+1}</span><span className="text-t-text">{item}</span></div>)}</div></aside></section>
  </div>;
}
